In [1]:
pip install pymongo

Collecting pymongo
  Downloading pymongo-4.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (670 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.1/670.1 kB 5.2 MB/s eta 0:00:00
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 7.4 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.6.1 pymongo-4.7.0

In [2]:
import pandas as pd
import numpy as np
import pymongo

Mongodb connection

In [3]:
conn=pymongo.MongoClient("mongodb://raji_sweeti:guvi2024@ac-nr8vpka-shard-00-00.vrmcz0d.mongodb.net:27017,ac-nr8vpka-shard-00-01.vrmcz0d.mongodb.net:27017,ac-nr8vpka-shard-00-02.vrmcz0d.mongodb.net:27017/?ssl=true&replicaSet=atlas-oe657d-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0")
db=conn['sample_airbnb']
col=db['listingsAndReviews']

Collecting data

In [4]:
airbnb_data = []
for i in col.find():
    data = dict(Listing_url = i['listing_url'],
                Name = i.get('name'),
                Property_type = i['property_type'],
                Room_type = i['room_type'],
                Bed_type = i['bed_type'],
                Min_nights = int(i['minimum_nights']),
                Max_nights = int(i['maximum_nights']),
                Cancellation_policy = i['cancellation_policy'],
                Accomodates = i['accommodates'],
                Total_bedrooms = i.get('bedrooms'),
                Total_beds = i.get('beds'),
                No_of_reviews = i['number_of_reviews'],
                Bathrooms = i.get('bathrooms'),
                Amenities = ', '.join(i['amenities']),
                Price = i['price'],
                Security_deposit = i.get('security_deposit'),
                Cleaning_fee = i.get('cleaning_fee'),
                Extra_people = i['extra_people'],
                Guests_included= i['guests_included'],
                Host_id = i['host']['host_id'],
                Host_name = i['host']['host_name'],
                Host_location = i['host']['host_location'],
                Host_response_time = i['host'].get('host_response_time'),
                Host_neighbourhood =  i['host']['host_neighbourhood'],
                Host_verification = ','.join(i['host']['host_verifications']),
                Street = i['address']['street'],
                Market = i['address']['market'],
                Country = i['address']['country'],
                Country_code = i['address']['country_code'],
                Longitude = i['address']['location']['coordinates'][0],
                Latitude = i['address']['location']['coordinates'][1],
                Is_location_exact = i['address']['location']['is_location_exact'],
                Availability_30= i['availability']['availability_30'],
                Availability_60 = i['availability']['availability_60'],
                Availability_90 = i['availability']['availability_90'],
                Availability_365 = i['availability']['availability_365'],
                Review_scores = i['review_scores'].get('review_scores_rating')
    )
    airbnb_data.append(data)

In [5]:
df=pd.DataFrame(airbnb_data)
df

,Listing_url,Name,Property_type,Room_type,Bed_type,Min_nights,Max_nights,Cancellation_policy,Accomodates,Total_bedrooms,...,Country,Country_code,Longitude,Latitude,Is_location_exact,Availability_30,Availability_60,Availability_90,Availability_365,Review_scores
0,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,House,Entire home/apt,Real Bed,2,30,moderate,8,3.0,...,Portugal,PT,-8.613080,41.141300,False,28,47,74,239,89.0
1,https://www.airbnb.com/rooms/10009999,Horto flat with small garden,Apartment,Entire home/apt,Real Bed,2,1125,flexible,4,1.0,...,Brazil,BR,-43.230750,-22.966254,True,0,0,0,0,NaN
2,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,2,1.0,...,United States,US,-157.839190,21.286340,True,16,46,76,343,84.0
3,https://www.airbnb.com/rooms/10021707,Private Room in Bushwick,Apartment,Private room,Real Bed,14,1125,flexible,1,1.0,...,United States,US,-73.936150,40.697910,True,0,0,0,0,100.0
4,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1,1125,flexible,2,1.0,...,Brazil,BR,-43.205047,-22.971951,True,28,58,88,363,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,https://www.airbnb.com/rooms/9983221,Cozy apartment downtown Porto,Apartment,Entire home/apt,Real Bed,3,1125,strict_14_with_grace_period,4,1.0,...,Portugal,PT,-8.616930,41.151370,False,26,51,77,300,98.0
5551,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1,1125,flexible,2,2.0,...,Turkey,TR,29.030790,40.985630,False,30,60,90,365,NaN
5552,https://www.airbnb.com/rooms/9987200,The best suite in Copacabana (total privacy),Aparthotel,Private room,Real Bed,3,60,flexible,3,1.0,...,Brazil,BR,-43.176533,-22.961076,True,7,29,53,53,97.0
5553,https://www.airbnb.com/rooms/9990304,March Madness Special! Aina Nalu Platinum D107,Condominium,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2.0,...,United States,US,-156.676460,20.875610,False,8,20,26,243,97.0
5554,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2.0,...,United States,US,-156.667520,20.858940,False,0,8,31,258,92.0

Cleaning dataset
1.missing values
2.duplicates
3.outliers
4.structured data
5.incorrect format

Checking format data types

In [6]:
df.dtypes

Listing_url             object
Name                    object
Property_type           object
Room_type               object
Bed_type                object
Min_nights               int64
Max_nights               int64
Cancellation_policy     object
Accomodates              int64
Total_bedrooms         float64
Total_beds             float64
No_of_reviews            int64
Bathrooms               object
Amenities               object
Price                   object
Security_deposit        object
Cleaning_fee            object
Extra_people            object
Guests_included         object
Host_id                 object
Host_name               object
Host_location           object
Host_response_time      object
Host_neighbourhood      object
Host_verification       object
Street                  object
Market                  object
Country                 object
Country_code            object
Longitude              float64
Latitude               float64
Is_location_exact         bool
Availability_30          int64
Availability_60          int64
Availability_90          int64
Availability_365         int64
Review_scores          float64
dtype: object

Converting incorrect data types

In [7]:

# Convert columns to relevant data types

df['Total_beds'] = df['Total_beds'][~df['Total_beds'].isna()].astype(int)
df['Bathrooms'] = df['Bathrooms'][~df['Bathrooms'].isna()].astype(str).astype(float).astype(int)

# Convert 'Price' column to float
df['Price'] = df['Price'].astype(str).astype(float)

# Convert 'Security_deposit' column to float, handling NaN values
df['Security_deposit'] = df['Security_deposit'][~df['Security_deposit'].isna()].astype(str).astype(float)

# Convert 'Cleaning_fee' column to float, handling NaN values
df['Cleaning_fee'] = df['Cleaning_fee'][~df['Cleaning_fee'].isna()].astype(str).astype(float)

# Convert 'Extra_people' column to float
df['Extra_people'] = df['Extra_people'].astype(str).astype(float).astype(int)

# Convert 'Guests_included' column to float
df['Guests_included'] = df['Guests_included'].astype(str).astype(float).astype(int)

# Convert 'Guests_included' column to float
df['Host_id'] = df['Host_id'].astype(str).astype(int)

In [8]:
df.dtypes

Listing_url             object
Name                    object
Property_type           object
Room_type               object
Bed_type                object
Min_nights               int64
Max_nights               int64
Cancellation_policy     object
Accomodates              int64
Total_bedrooms         float64
Total_beds             float64
No_of_reviews            int64
Bathrooms              float64
Amenities               object
Price                  float64
Security_deposit       float64
Cleaning_fee           float64
Extra_people             int64
Guests_included          int64
Host_id                  int64
Host_name               object
Host_location           object
Host_response_time      object
Host_neighbourhood      object
Host_verification       object
Street                  object
Market                  object
Country                 object
Country_code            object
Longitude              float64
Latitude               float64
Is_location_exact         bool
Availability_30          int64
Availability_60          int64
Availability_90          int64
Availability_365         int64
Review_scores          float64
dtype: object

In [9]:
c=list(df.columns)

In [10]:
c

['Listing_url',
 'Name',
 'Property_type',
 'Room_type',
 'Bed_type',
 'Min_nights',
 'Max_nights',
 'Cancellation_policy',
 'Accomodates',
 'Total_bedrooms',
 'Total_beds',
 'No_of_reviews',
 'Bathrooms',
 'Amenities',
 'Price',
 'Security_deposit',
 'Cleaning_fee',
 'Extra_people',
 'Guests_included',
 'Host_id',
 'Host_name',
 'Host_location',
 'Host_response_time',
 'Host_neighbourhood',
 'Host_verification',
 'Street',
 'Market',
 'Country',
 'Country_code',
 'Longitude',
 'Latitude',
 'Is_location_exact',
 'Availability_30',
 'Availability_60',
 'Availability_90',
 'Availability_365',
 'Review_scores']

Missing values

In [11]:
df.isnull().sum()

Listing_url               0
Name                      0
Property_type             0
Room_type                 0
Bed_type                  0
Min_nights                0
Max_nights                0
Cancellation_policy       0
Accomodates               0
Total_bedrooms            5
Total_beds               13
No_of_reviews             0
Bathrooms                10
Amenities                 0
Price                     0
Security_deposit       2084
Cleaning_fee           1531
Extra_people              0
Guests_included           0
Host_id                   0
Host_name                 0
Host_location             0
Host_response_time     1388
Host_neighbourhood        0
Host_verification         0
Street                    0
Market                    0
Country                   0
Country_code              0
Longitude                 0
Latitude                  0
Is_location_exact         0
Availability_30           0
Availability_60           0
Availability_90           0
Availability_365          0
Review_scores          1474
dtype: int64

In [12]:
df.isna().sum()

Listing_url               0
Name                      0
Property_type             0
Room_type                 0
Bed_type                  0
Min_nights                0
Max_nights                0
Cancellation_policy       0
Accomodates               0
Total_bedrooms            5
Total_beds               13
No_of_reviews             0
Bathrooms                10
Amenities                 0
Price                     0
Security_deposit       2084
Cleaning_fee           1531
Extra_people              0
Guests_included           0
Host_id                   0
Host_name                 0
Host_location             0
Host_response_time     1388
Host_neighbourhood        0
Host_verification         0
Street                    0
Market                    0
Country                   0
Country_code              0
Longitude                 0
Latitude                  0
Is_location_exact         0
Availability_30           0
Availability_60           0
Availability_90           0
Availability_365          0
Review_scores          1474
dtype: int64

In [13]:
if df.isna().sum().any() > 0:
    print("Columns with missing Nan values:")
    Nan=df.columns[df.isna().any()].tolist()
    print(Nan)

Columns with missing Nan values:
['Total_bedrooms', 'Total_beds', 'Bathrooms', 'Security_deposit', 'Cleaning_fee', 'Host_response_time', 'Review_scores']

In [14]:
#categorical data columns
cat_col=cat_col = df.select_dtypes(include=['object', 'bool']).columns
cat_col

Index(['Listing_url', 'Name', 'Property_type', 'Room_type', 'Bed_type',
       'Cancellation_policy', 'Amenities', 'Host_name', 'Host_location',
       'Host_response_time', 'Host_neighbourhood', 'Host_verification',
       'Street', 'Market', 'Country', 'Country_code', 'Is_location_exact'],
      dtype='object')

In [15]:
#continous data column
cont_col=df.select_dtypes(exclude=['object','bool']).columns
columns_to_remove = ['Host_id', 'Longitude', 'Latitude']
cont_col=cont_col.drop(columns_to_remove)
cont_col

Index(['Min_nights', 'Max_nights', 'Accomodates', 'Total_bedrooms',
       'Total_beds', 'No_of_reviews', 'Bathrooms', 'Price', 'Security_deposit',
       'Cleaning_fee', 'Extra_people', 'Guests_included', 'Availability_30',
       'Availability_60', 'Availability_90', 'Availability_365',
       'Review_scores'],
      dtype='object')

Checking outliers
if max is greater than upper hreshold or min is smaller than lower threshold there is a outlier

In [16]:

for column in cont_col:

    print(f"Column : {column}")

    iqr = df[column].quantile(0.75) - df[column].quantile(0.25)
    upper_threshold = df[column].quantile(0.75) + (1.5 * iqr)
    lower_threshold = df[column].quantile(0.25) - (1.5 * iqr)
    print(f"UpperThreshold : {upper_threshold} and lowerThreshold : {lower_threshold}")
    print(df[column].describe())

    print('**********************')

Column : Min_nights
UpperThreshold : 6.0 and lowerThreshold : -2.0
count    5555.000000
mean        5.564356
std        22.613861
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max      1250.000000
Name: Min_nights, dtype: float64
**********************
Column : Max_nights
UpperThreshold : 2724.0 and lowerThreshold : -1540.0
count    5.555000e+03
mean     1.382776e+06
std      5.256920e+07
min      1.000000e+00
25%      5.900000e+01
50%      1.125000e+03
75%      1.125000e+03
max      2.147484e+09
Name: Max_nights, dtype: float64
**********************
Column : Accomodates
UpperThreshold : 7.0 and lowerThreshold : -1.0
count    5555.000000
mean        3.505851
std         2.297019
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        16.000000
Name: Accomodates, dtype: float64
**********************
Column : Total_bedrooms
UpperThreshold : 3.5 and lowerThreshold : -0.5
count    5550.000000
mean        1.411712
std         1.041942
min         0.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        20.000000
Name: Total_bedrooms, dtype: float64
**********************
Column : Total_beds
UpperThreshold : 6.0 and lowerThreshold : -2.0
count    5542.000000
mean        2.071454
std         1.619660
min         0.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        25.000000
Name: Total_beds, dtype: float64
**********************
Column : No_of_reviews
UpperThreshold : 78.5 and lowerThreshold : -45.5
count    5555.000000
mean       27.606481
std        49.798376
min         0.000000
25%         1.000000
50%         5.000000
75%        32.000000
max       533.000000
Name: No_of_reviews, dtype: float64
**********************
Column : Bathrooms
UpperThreshold : 1.0 and lowerThreshold : 1.0
count    5545.000000
mean        1.258611
std         0.684179
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max        16.000000
Name: Bathrooms, dtype: float64
**********************
Column : Price
UpperThreshold : 595.0 and lowerThreshold : -245.0
count     5555.000000
mean       278.766157
std        842.215531
min          9.000000
25%         70.000000
50%        129.000000
75%        280.000000
max      48842.000000
Name: Price, dtype: float64
**********************
Column : Security_deposit
UpperThreshold : 1250.0 and lowerThreshold : -750.0
count     3471.000000
mean       509.430424
std       1594.805320
min          0.000000
25%          0.000000
50%        200.000000
75%        500.000000
max      39228.000000
Name: Security_deposit, dtype: float64
**********************
Column : Cleaning_fee
UpperThreshold : 288.0 and lowerThreshold : -136.0
count    4024.000000
mean       94.074801
std       110.203782
min         0.000000
25%        23.000000
50%        60.000000
75%       129.000000
max      2000.000000
Name: Cleaning_fee, dtype: float64
**********************
Column : Extra_people
UpperThreshold : 50.0 and lowerThreshold : -30.0
count    5555.000000
mean       22.791899
std        69.331511
min         0.000000
25%         0.000000
50%         0.000000
75%        20.000000
max      2346.000000
Name: Extra_people, dtype: float64
**********************
Column : Guests_included
UpperThreshold : 3.5 and lowerThreshold : -0.5
count    5555.000000
mean        1.747435
std         1.487352
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        16.000000
Name: Guests_included, dtype: float64
**********************
Column : Availability_30
UpperThreshold : 60.0 and lowerThreshold : -36.0
count    5555.000000
mean       11.816202
std        11.686113
min         0.000000
25%         0.000000
50%         8.000000
75%        24.000000
max        30.000000
Name: Availability_30, dtype: float64
**********************
Column : Availability_60
UpperThreshold : 130.0 and lowerThreshold : -78.0
count    5555.000000
mean       26.451305
std        23.476011
min         0.000000
25%         0.000000
50%        23.000000
75%        52.000000
max        60.000000
Name: Availability_60, dtype: float64
**********************
Column : Availability_90
UpperThreshold : 200.0 and lowerThreshold : -120.0
count    5555.000000
mean       42.758056
std        35.226897
min         0.000000
25%         0.000000
50%        43.000000
75%        80.000000
max        90.000000
Name: Availability_90, dtype: float64
**********************
Column : Availability_365
UpperThreshold : 767.0 and lowerThreshold : -433.0
count    5555.000000
mean      173.105671
std       139.841893
min         0.000000
25%        17.000000
50%       171.000000
75%       317.000000
max       365.000000
Name: Availability_365, dtype: float64
**********************
Column : Review_scores
UpperThreshold : 112.5 and lowerThreshold : 76.5
count    4081.000000
mean       93.099240
std         9.023483
min        20.000000
25%        90.000000
50%        95.000000
75%        99.000000
max       100.000000
Name: Review_scores, dtype: float64
**********************

Filling missing values

In [17]:
# Fill missing values in 'Total_bedrooms' with the mode
df['Total_bedrooms'].fillna(df['Total_bedrooms'].median(), inplace=True)

# Fill missing values in 'Total_beds' with the median due to outliers
df['Total_beds'].fillna(df['Total_beds'].median(), inplace=True)

df['Bathrooms'].fillna(df['Bathrooms'].median(), inplace=True)

# Fill missing values in 'Security_deposit' with the median due to outliers
df['Security_deposit'].fillna(df['Security_deposit'].median(), inplace=True)

# Fill missing values in 'Cleaning_fee' with the median due to outliers
df['Cleaning_fee'].fillna(df['Cleaning_fee'].median(), inplace=True)

# Fill missing values in 'Review_scores' with the median due to outliers
df['Review_scores'].fillna(df['Review_scores'].median(), inplace=True)

In [18]:
df['Host_response_time'].fillna(df['Host_response_time'].mode()[0], inplace=True)

In [19]:
if df.isna().sum().any() > 0:
    print("Columns with missing Nan values:")
    Nan=df.columns[df.isna().any()].tolist()
    print(Nan)

In [20]:
# Check for empty strings in each cell of the DataFrame
empty_strings = df.applymap(lambda x: x == '')

# Get the column names with empty strings
columns_with_empty_strings = empty_strings.any()

# Print the column names with empty strings
print("Columns with empty strings:")
print(columns_with_empty_strings[columns_with_empty_strings].index.tolist())

Columns with empty strings:
['Name', 'Amenities', 'Host_location', 'Host_neighbourhood', 'Host_verification', 'Market']

In [21]:
df["Name"].replace({'':"Not Specified"},inplace=True)
df["Amenities"].replace({'':"Not Specified"},inplace=True)
df["Host_location"].replace({'':"Not Specified"},inplace=True)
df["Host_neighbourhood"].replace({'':"Not Specified"},inplace=True)
df["Host_verification"].replace({'':"Not Specified"},inplace=True)
df["Market"].replace({'':"Not Specified"},inplace=True)

In [22]:
# Check for empty strings in each cell of the DataFrame
empty_strings = df.applymap(lambda x: x == '')

# Get the column names with empty strings
columns_with_empty_strings = empty_strings.any()

# Print the column names with empty strings
print("Columns with empty strings:")
print(columns_with_empty_strings[columns_with_empty_strings].index.tolist())

Columns with empty strings:
[]

Checking if duplicates exist

In [23]:
df.shape

(5555, 37)

In [24]:
df.drop_duplicates
df.shape

(5555, 37)

Removing outliers and checking

In [25]:

for column in cont_col:

    print(f"Column : {column}")

    iqr = df[column].quantile(0.75) - df[column].quantile(0.25)
    upper_threshold = df[column].quantile(0.75) + (1.5 * iqr)
    lower_threshold = df[column].quantile(0.25) - (1.5 * iqr)
    print(f"UpperThreshold : {upper_threshold} and lowerThreshold : {lower_threshold}")

    df[column] = df[column].clip(lower_threshold, upper_threshold)   #cliping- removing outliers
    print(df[column].describe())


    print('**********************')

Column : Min_nights
UpperThreshold : 6.0 and lowerThreshold : -2.0
count    5555.000000
mean        2.609001
std         1.704954
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         6.000000
Name: Min_nights, dtype: float64
**********************
Column : Max_nights
UpperThreshold : 2724.0 and lowerThreshold : -1540.0
count    5555.000000
mean      712.823402
std       519.587550
min         1.000000
25%        59.000000
50%      1125.000000
75%      1125.000000
max      2724.000000
Name: Max_nights, dtype: float64
**********************
Column : Accomodates
UpperThreshold : 7.0 and lowerThreshold : -1.0
count    5555.000000
mean        3.329613
std         1.784152
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         7.000000
Name: Accomodates, dtype: float64
**********************
Column : Total_bedrooms
UpperThreshold : 3.5 and lowerThreshold : -0.5
count    5555.000000
mean        1.363726
std         0.847622
min         0.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         3.500000
Name: Total_bedrooms, dtype: float64
**********************
Column : Total_beds
UpperThreshold : 6.0 and lowerThreshold : -2.0
count    5555.000000
mean        2.011341
std         1.347872
min         0.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         6.000000
Name: Total_beds, dtype: float64
**********************
Column : No_of_reviews
UpperThreshold : 78.5 and lowerThreshold : -45.5
count    5555.000000
mean       20.341764
std        27.296527
min         0.000000
25%         1.000000
50%         5.000000
75%        32.000000
max        78.500000
Name: No_of_reviews, dtype: float64
**********************
Column : Bathrooms
UpperThreshold : 1.0 and lowerThreshold : 1.0
count    5555.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: Bathrooms, dtype: float64
**********************
Column : Price
UpperThreshold : 595.0 and lowerThreshold : -245.0
count    5555.000000
mean      202.018902
std       179.638141
min         9.000000
25%        70.000000
50%       129.000000
75%       280.000000
max       595.000000
Name: Price, dtype: float64
**********************
Column : Security_deposit
UpperThreshold : 475.0 and lowerThreshold : -125.0
count    5555.000000
mean      206.240324
std       155.433285
min         0.000000
25%       100.000000
50%       200.000000
75%       250.000000
max       475.000000
Name: Security_deposit, dtype: float64
**********************
Column : Cleaning_fee
UpperThreshold : 197.5 and lowerThreshold : -62.5
count    5555.000000
mean       74.109091
std        56.717591
min         0.000000
25%        35.000000
50%        60.000000
75%       100.000000
max       197.500000
Name: Cleaning_fee, dtype: float64
**********************
Column : Extra_people
UpperThreshold : 50.0 and lowerThreshold : -30.0
count    5555.000000
mean       12.756796
std        18.030665
min         0.000000
25%         0.000000
50%         0.000000
75%        20.000000
max        50.000000
Name: Extra_people, dtype: float64
**********************
Column : Guests_included
UpperThreshold : 3.5 and lowerThreshold : -0.5
count    5555.000000
mean        1.553555
std         0.857387
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         3.500000
Name: Guests_included, dtype: float64
**********************
Column : Availability_30
UpperThreshold : 60.0 and lowerThreshold : -36.0
count    5555.000000
mean       11.816202
std        11.686113
min         0.000000
25%         0.000000
50%         8.000000
75%        24.000000
max        30.000000
Name: Availability_30, dtype: float64
**********************
Column : Availability_60
UpperThreshold : 130.0 and lowerThreshold : -78.0
count    5555.000000
mean       26.451305
std        23.476011
min         0.000000
25%         0.000000
50%        23.000000
75%        52.000000
max        60.000000
Name: Availability_60, dtype: float64
**********************
Column : Availability_90
UpperThreshold : 200.0 and lowerThreshold : -120.0
count    5555.000000
mean       42.758056
std        35.226897
min         0.000000
25%         0.000000
50%        43.000000
75%        80.000000
max        90.000000
Name: Availability_90, dtype: float64
**********************
Column : Availability_365
UpperThreshold : 767.0 and lowerThreshold : -433.0
count    5555.000000
mean      173.105671
std       139.841893
min         0.000000
25%        17.000000
50%       171.000000
75%       317.000000
max       365.000000
Name: Availability_365, dtype: float64
**********************
Column : Review_scores
UpperThreshold : 105.5 and lowerThreshold : 85.5
count    5555.000000
mean       94.536364
std         4.327375
min        85.500000
25%        93.000000
50%        95.000000
75%        98.000000
max       100.000000
Name: Review_scores, dtype: float64
**********************

In [26]:
df['Total_bedrooms'] = df['Total_bedrooms'].astype(int)
df['Total_beds'] = df['Total_beds'].astype(int)
df['Bathrooms'] = df['Bathrooms'].astype(str).astype(float).astype(int)

In [27]:
df.dtypes

Listing_url             object
Name                    object
Property_type           object
Room_type               object
Bed_type                object
Min_nights               int64
Max_nights               int64
Cancellation_policy     object
Accomodates              int64
Total_bedrooms           int64
Total_beds               int64
No_of_reviews          float64
Bathrooms                int64
Amenities               object
Price                  float64
Security_deposit       float64
Cleaning_fee           float64
Extra_people             int64
Guests_included        float64
Host_id                  int64
Host_name               object
Host_location           object
Host_response_time      object
Host_neighbourhood      object
Host_verification       object
Street                  object
Market                  object
Country                 object
Country_code            object
Longitude              float64
Latitude               float64
Is_location_exact         bool
Availability_30          int64
Availability_60          int64
Availability_90          int64
Availability_365         int64
Review_scores          float64
dtype: object

In [28]:
df['Guests_included'] = df['Guests_included'].astype(int)   # while cliping converted as float changing to int

In [29]:
df.dtypes

Listing_url             object
Name                    object
Property_type           object
Room_type               object
Bed_type                object
Min_nights               int64
Max_nights               int64
Cancellation_policy     object
Accomodates              int64
Total_bedrooms           int64
Total_beds               int64
No_of_reviews          float64
Bathrooms                int64
Amenities               object
Price                  float64
Security_deposit       float64
Cleaning_fee           float64
Extra_people             int64
Guests_included          int64
Host_id                  int64
Host_name               object
Host_location           object
Host_response_time      object
Host_neighbourhood      object
Host_verification       object
Street                  object
Market                  object
Country                 object
Country_code            object
Longitude              float64
Latitude               float64
Is_location_exact         bool
Availability_30          int64
Availability_60          int64
Availability_90          int64
Availability_365         int64
Review_scores          float64
dtype: object

In [30]:
df.to_csv("airbnb_analysis_data.csv",index=False)